version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
