linters:
  disable:
    - exhaustive
    - funlen
    - contextcheck
    - wastedassign
    - gci
    - depguard
    - tagalign
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - test
    - unused
  fast: true
linters-settings:
  gosec:
    config:
      G306: "0644"
