version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - cyclop
    - gocheckcompilerdirectives
    - gocognit
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - gomodguard
    - maintidx
    - misspell
    - nestif
    - prealloc
    - testableexamples
    - testpackage
  disable:
    - contextcheck
    - depguard
    - dupword
    - errcheck
    - exhaustive
    - funlen
    - govet
    - staticcheck
    - tagalign
    - unused
    - wastedassign
  settings:
    gosec:
      config:
        G306: "0644"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
