linters:
  disable:
    - scopelint
    - exhaustive
    - funlen
  enable:
    - dupl
    - forcetypeassert
    - goconst
    - godot
    - goimports
    - ifshort
    - importas
    - misspell
    - nakedret
    - nolintlint
    - predeclared
    - thelper
    - unconvert
    - wastedassign
  presets:
    - bugs
    - unused
    - complexity
  fast: false
linters-settings:
  gosec:
    config:
      G306: "0644"