version: "3"

silent: true

vars:
  NAME: lembrol
  GOLANGCI_LINT_VERSION: 2.5.0
  PACKAGES: ./...
  VERSION:
    sh: cat .bumpversion.cfg | grep current_version | awk '{print $3}'

tasks:
  clean:
    desc: Remove build artifacts and cached data
    cmds:
      - rm -rf dist
      - rm -f coverage* *.log
      - go clean -cache -testcache -modcache

  dev:
    desc: Prepare development environment and tooling
    cmds: 
      - go mod download
      - mkdir -p dist
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b dist v{{.GOLANGCI_LINT_VERSION}}

  upgrade:
    desc: Upgrade dependencies
    cmds:
      - go run github.com/oligot/go-mod-upgrade@latest
      - go mod tidy

  format:
    desc: Format source files
    cmds:
      - go run golang.org/x/tools/cmd/goimports@latest -l -w .
      - go run mvdan.cc/gofumpt@latest -l -w .
      - go mod tidy -v

  lint:
    desc: Run static analysis checks
    cmds:
      - go mod verify
      - go vet {{.PACKAGES}}
      - ./dist/golangci-lint run

  audit:
    desc: Scan dependencies for known vulnerabilities
    cmds:
      - go run golang.org/x/vuln/cmd/govulncheck@latest {{.PACKAGES}}

  test:
    desc: Run tests with coverage
    cmds:
      - mkdir -p dist
      - go test -buildvcs -race -shuffle=on -cover -coverprofile=dist/coverage.out {{.PACKAGES}} {{.CLI_ARGS}} 

  test-coverage:
    desc: Open HTML coverage report
    deps:
      - test
    cmds:
      - go tool cover -html=dist/coverage.out

  run:
    desc: Run the application in development mode
    cmds:
      - go run ./cmd/{{.NAME}} --debug {{.CLI_ARGS}}

  build:
    desc: Build the binary
    cmds:
      - mkdir -p dist
      - go build -ldflags='-s -w -extldflags "-static"' -o dist/{{.NAME}} ./cmd/{{.NAME}}/
    env:
      CGO_ENABLED: 0
      GOOS: "{{.GOOS}}"
      GOARCH: "{{.GOARCH}}"

  release:
    desc: Create a tagged release
    cmds:
      - git flow init -d
      - grep -q '\[Unreleased\]' CHANGELOG.md || (echo 'Create the [Unreleased] section in the changelog first!' && exit 1)
      - bumpversion --verbose --tag --commit {{.CLI_ARGS}}
      - git flow release start {{.VERSION}}
      - GIT_MERGE_AUTOEDIT=no git flow release finish -m "Merge branch release/{{.VERSION}}" -T {{.VERSION}} {{.VERSION}} -p

  goreleaser:
    desc: Create a snapshot build via GoReleaser
    cmds:
      - go run github.com/goreleaser/goreleaser@latest build --clean --snapshot --single-target
