version: "3"

silent: true

vars:
  NAME: "lembrol"
  PACKAGE: "./..."
  DIST: "dist"

tasks:
  clean:
    desc: delete binary and development environment
    cmds:
      - rm coverage* 2> /dev/null || true
      - rm *.log 2> /dev/null || true
      - go clean -cache -testcache -modcache

  dev:
    desc: prepare development environment
    cmds: 
      - go mod download
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $GOBIN v2.1.6

  upgrade:
    desc: list direct dependencies that have upgrades available
    cmds:
      - go run github.com/oligot/go-mod-upgrade@latest
      - go mod tidy

  format:
    desc: format files
    cmds:
      - go run golang.org/x/tools/cmd/goimports@latest -l -w .
      - go run mvdan.cc/gofumpt@latest -l -w .
      - go mod tidy -v

  lint:
    desc: run static checks
    cmds:
      - golangci-lint run

  test:
    desc: "run tests"
    cmds:
      - go test {{.CLI_ARGS} -race -shuffle=on -cover -coverprofile=/{{.DIST}}/coverage.out {{.PACKAGE}}
      - go tool cover -html=/{{.DIST}}/coverage.out

  audit:
    desc: run quality control checks
    cmds:
      - go mod verify
      - go vet {{.PACKAGES}}
      - go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 {{.PACKAGES}}
      - go run golang.org/x/vuln/cmd/govulncheck@latest {{.PACKAGES}}

  run:
    desc: run the application
    cmds:
      - go run ./cmd/lembrol --log {{.CLI_ARGS}}

  build:
    desc: create snapshot release
    cmds:
      - go run github.com/goreleaser/goreleaser@latest build --clean --snapshot --single-target

  release:
    desc: create a new release
    cmds:
      - git flow init -d
      - |
        if ! grep -q '\[Unreleased\]' CHANGELOG.md; then
          echo 'Create the [Unreleased] section in the changelog first!' && exit 1
        fi
      - bumpversion --verbose --tag --commit {{.CLI_ARGS}}
      - git flow release start $(VERSION)
      - GIT_MERGE_AUTOEDIT=no git flow release finish -m "Merge branch release/$(VERSION)" -T $(VERSION) $(VERSION) -p
