name: Test

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'
          cache: true

      - name: install task
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest

      - name: run test
        run: |
          task test -- -short
